name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t aryanchaudhary449/bot1:v3
    - name: login
      run: docker login -u aryanchaudhary449 -p Aaryanaryan && docker push aryanchaudhary449/bot1:v3
